added error text
ForeverYoung1208/clmasters pull request #10
Opened 2021-01-03 16:34 UTC by ForeverYoung1208

Просто добавил еще один перевод ошибки.

2021-01-05 15:04 UTC, yelyzavetak requested changes

2021-01-05 15:04 UTC, yelyzavetak commented on client/src/pages/AdminPage/CitiesBlock/CitiesBlock.jsx
> +    console.log('[formData]', formData)
Зачем консоль лог?

2021-01-05 16:45 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/CitiesBlock/CitiesBlock.jsx
> +    console.log('[formData]', formData)
пффф не заметил. Убрал.

2021-01-06 15:01 UTC, yelyzavetak approved these changes

2021-01-08 19:05 UTC, merged