Feature/material
ForeverYoung1208/clmasters pull request #12
Opened 2021-01-10 22:15 UTC by ForeverYoung1208

Пулл реквест чтобы показать что я жив. Может, не стоит это смотреть, надеюсь на неделе выделить время, причухать, хотя бы довести админку городов до ума.

По сути изменений - хоть они и направлены на переход на material-ui, но по пути решил менять парадигму и отказываться от 'sectionKey'. Чтбы 2 раза не вставать -  именения интерфейса все равно затрагивают изменения логики.

Менял пока только в части admin/cities. 
То есть вычленил администрирование cities отдельно, создал для них свой redux state, экшкны, вызовы API ...
весь интерфейс в части cities переписал на material. 

Кнопки поменял везде, через адаптацию своего элемента.

Целый день (!!!) провозился со стилизацией MUI  dataGrid (жалуюсь, намучился)... сделал, как мне кажется, костыль. 

Не всё закончил даже с админкой городов, хоть осталось и чуть чуть, но не успел. 

... К сожалению, некоторые файлы были затронуты prettier -ом без смысловых изменний...

2021-01-11 16:05 UTC, yelyzavetak requested changes

2021-01-11 16:05 UTC, yelyzavetak commented on client/src/pages/AdminPage/AdminPage.jsx
> +// import React from 'react'
В конечном итоге удали пожалуйста все закомментированные части кода, когда до точки допишешь

2021-01-11 16:05 UTC, yelyzavetak commented on client/src/pages/AdminPage/CitiesBlock/CityEditDialog/CityEditDialog.jsx
> +    cities?.data.find((c) => +c.id === +cityId)
Используй деструктор

2021-01-11 16:05 UTC, yelyzavetak commented on client/src/pages/AdminPage/CitiesBlock/CityEditDialog/__old__CityEditForm.jsx
> +export default old_reduxForm({
к чему переименование?

2021-01-14 19:56 UTC, ForeverYoung1208 commented on client/package.json
> +    "@material-ui/data-grid": "^4.0.0-alpha.15",
data-grid как - то больше функционала... фильтры, сортировки из коробки.

2021-01-14 19:56 UTC, ForeverYoung1208 commented on client/src/components/Button/Button.jsx
> +import MaterialButton from '@material-ui/core/Button'
ок сенк.

2021-01-14 19:59 UTC, ForeverYoung1208 commented on client/src/components/ItemsList/Item/Item.jsx
> +import DeleteIcon from '@material-ui/icons/Delete'
ок. Если не секрет, это просто стилевой момент, для читабельности кода, или есть какая - то техническая разница?

2021-01-14 19:59 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/AdminPage.jsx
> +// import React from 'react'
ессно.

2021-01-14 20:18 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/CitiesBlock/CityEditDialog/CityEditDialog.jsx
> +    cities?.data.find((c) => +c.id === +cityId)
Ок.

2021-01-14 20:22 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/CitiesBlock/CityEditDialog/__old__CityEditForm.jsx
> +export default old_reduxForm({
пока не закончил рефакторинг, оставил старый вариант, может, подсмотреть чего или вспомнить надо. Чтобы автокомплит Visual Studio  случайно не подставил куда- то импорт формы из старого файла, переименовал и сам экспорт. Когда доделаю, удалю весь файл.

2021-01-15 14:23 UTC, yelyzavetak commented on client/src/components/ItemsList/Item/Item.jsx
> +import DeleteIcon from '@material-ui/icons/Delete'
Это просто для лучшей читабельности, в коммерческих проектах иногда даже требуют правильный порядок импортов в файлах, например:
Импорт сторонних библиотек
Импорт типов
Импорт констант
Импорт внутренных компонентов

В данном случае это не обязательно, но для лучшей стилистики кода лучше следовать этому замечанию с кнопками. С тех стороны нет разницы

2021-01-21 16:17 UTC, ForeverYoung1208 commented
Закончил с admin/cities 
Хотелось бы понять, я в принципе на правильном пути? Как в части использования материала, так и сруктурно.
Если да, то распространю практику на все разделы админки.

Ну а потом уже за саму форму поиска мастеров и общий макет станички.

2021-01-22 14:17 UTC, yelyzavetak commented on client/src/pages/AdminPage/AdminPage.jsx
> +        {/* </Card> */}
Зачем тут закомментированные куски?

2021-01-22 14:18 UTC, yelyzavetak commented on client/src/pages/AdminPage/AdminPage.jsx
> +// import React from 'react'
Так а чего не удалил?

2021-01-22 14:20 UTC, yelyzavetak commented on client/src/pages/AdminPage/CitiesBlock/CitiesBlock.jsx
> +    dispatch(setErrorMessage(''))
ВОзможно стоит для удаления и редактирования сделать useEffect, который будет вызывать dispatch(setErrorMessage('')) при любом изменении id

2021-01-22 14:21 UTC, yelyzavetak commented on client/src/pages/AdminPage/CitiesBlock/CitiesBlock.jsx
> +    if (citiesStatus === 'idle') {
idle - что это?

2021-01-22 14:22 UTC, yelyzavetak commented on client/src/pages/AdminPage/CitiesBlock/CitiesBlock.jsx
> +      renderCell: ({ row }) => (
renderCell - лучше вынести в отдельную функцию

2021-01-22 14:22 UTC, yelyzavetak commented on client/src/pages/AdminPage/CitiesBlock/CitiesBlock.jsx
> +          rowsPerPageOptions={[10, 20, 50]}
В константы

2021-01-22 14:24 UTC, yelyzavetak commented on client/src/pages/AdminPage/CitiesBlock/CityEditDialog/CityEditDialog.jsx
> +    data.find((c) => +c.id === +cityId),
Лучше деструктуризовать

2021-01-22 14:24 UTC, yelyzavetak commented on client/src/shared/js/api/adminData.js
> +    // myHttp('/api/cities', 'GET').then(x => x.json()),
Почему закомментировал?

2021-01-22 14:25 UTC, yelyzavetak commented on client/src/shared/js/common.js
> +  someErrors.forEach((e) => {
Деструктор

2021-01-22 14:25 UTC, yelyzavetak commented on client/src/shared/js/common.js
> +    if (e.message && e.path) {
Почему ошибка имеет разные поля?

2021-01-22 14:26 UTC, yelyzavetak commented on client/src/shared/themes/mainTheme.js
> +    divider: '#875b20',
Все цвета лучше повыносить в константы. Нужно проверить, как это делать правильно в материале и объявить глобальные цвета правильно

2021-01-22 14:26 UTC, yelyzavetak commented on client/src/store/actions/actionTypes/cities.js
> +// export const CITIES_FETCH_OK = 'cities/FETCH_OK'
?

2021-01-22 14:27 UTC, yelyzavetak commented on client/src/store/actions/cities.js
> +  const { cities } = await apiGetCities()
Ты их обворачиваешь в объект, а потом достаешь из объекта. Возвращай сразу cities

2021-01-22 14:27 UTC, yelyzavetak commented on client/src/store/reducers/admin.js
> +
Зачем тут пробелы?

2021-01-22 14:29 UTC, yelyzavetak commented on client/src/store/reducers/cities.js
> +const initialState = {
Используй деструкторы по возможности, и что такое idle? На какие значения эта переменная может еще меняться? Возможно стоит вынести эти значения в константы?

2021-01-22 14:29 UTC, yelyzavetak commented on client/src/store/reducers/cities.js
> +    case 'cities/fetch/fulfilled':
Все константы экшенов должны храниться в константах

2021-01-22 14:30 UTC, yelyzavetak commented on server/package.json
> +    "@material-ui/lab": "^4.0.0-alpha.57",
А зачем на беке материал?

2021-01-22 15:34 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/AdminPage.jsx
> +// import React from 'react'
возможно, что то пропустил.

2021-01-22 15:36 UTC, ForeverYoung1208 commented on client/package.json
> +    "react-draggable": "^4.4.3",
Интересно было попробовать как оно работает. Материал.. новая игрушка. 
Ну и прикольно же.

2021-01-23 17:49 UTC, ForeverYoung1208 commented on client/src/components/ItemsList/Item/Item.jsx
> +import { Edit as EditIcon } from '@material-ui/icons';
+

2021-01-23 18:08 UTC, ForeverYoung1208 commented on client/src/components/ItemsList/Item/Item.jsx
> +        fieldKeys.map((fieldKey) => {
Это остаток старой логики,самописной таблицы прзентации данных (ItmesList).  Я ж от ItemsList и Items буду отказыватья (заменяется на material-ui  DataGrid ), вот cities этим коммитом уже не используют ни ItemsList ни Items. Тк что неактуално, подлежит выпиливанию. 
Но, чисто для справки, как это раннее было: эта функция  забирается из пропа конфигурации fields и (если есть, ожидается как 3й элемент массива) применяется к данным поля для их трансформации в формат отображения.
Короче, функция - форматтер, если данные перед отображением надо как -то преобразовать. 

Выносится в отдельный const перед вызовом просто для читабельности, и для того чтобы в случае если она не определена избавиться от ошибки null is not a function. (наверное)
возможно, лучше было бы при вызове проверять transformFunc && transformFunc(item[fieldKey])

2021-01-23 18:11 UTC, ForeverYoung1208 commented on client/src/components/Material/DraggablePaper/DraggablePaper.jsx
> +import React from 'react'
Ну, много чего не было в задаче - весь UI чисто моя фантазия, позволил себе немного побаловаться.

2021-01-23 18:13 UTC, ForeverYoung1208 commented on client/src/components/Material/TabPanel/TabPanel.jsx
> +  const { children, selectedTab, index } = props
ok

2021-01-23 19:31 UTC, ForeverYoung1208 commented on client/src/components/ReduxForm/RenderFieldInput/RenderFieldInputMUI.jsx
> +  const isError = !!(touched && (error || warning))
ок.  
// в данном случае, мне кажется, стоимость вычислений ничтожна, но для привычки, наверное полезно.

2021-01-23 19:31 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/AdminPage.jsx
> +// import AppBar from '@material-ui/core/AppBar';
пропустил. Убрал.

2021-01-23 19:37 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/AdminPage.jsx
> +import Tabs from '@material-ui/core/Tabs'
мда, не нашел как автоинпут перенастроить, приходится руками поправлять.

2021-01-23 19:37 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/AdminPage.jsx
> +        {/* </Card> */}
убрал

2021-01-23 19:40 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/CitiesBlock/CitiesBlock.jsx
> +  const [editingCityId, setEditingCityId] = React.useState(null)
угу. Странно. Откуда оно взялось.

2021-01-23 19:51 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/CitiesBlock/CitiesBlock.jsx
> +    dispatch(setErrorMessage(''))
Мне кажется, будет не совсем прозрачная логика (причем id к ошибке - это еще надо понять), да и в зависимость useEffect надо добавлять все три переменные локального состояния  - editingCityId, deletingCityId, addingCityId
Могу переделать, если скажешь, конечно, но такое дело.
А вот имя переменной addingCityId поменяю, чет меня торкнуло так назвать, путает же.

2021-01-23 20:37 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/CitiesBlock/CitiesBlock.jsx
> +  const closeAddHandler = () => {
ок.

2021-01-23 20:57 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/CitiesBlock/CitiesBlock.jsx
> +    if (citiesStatus === 'idle') {
переименовал в 'pristine', так точнее отражает суть.
По сути это - статус стейта cities. Чтобы забирало данные только при первом рендере (иначе уходит в цикл).

2021-01-23 21:27 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/CitiesBlock/CitiesBlock.jsx
> +      renderCell: ({ row }) => (
ok

2021-01-23 21:34 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/CitiesBlock/CitiesBlock.jsx
> +          rowsPerPageOptions={[10, 20, 50]}
ок

2021-01-23 21:37 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/CitiesBlock/CityEditDialog/CityEditDialog.jsx
> +    data.find((c) => +c.id === +cityId),
да куда уж дальше деструктурировать...
разве что  убрал массив.

2021-01-23 21:38 UTC, ForeverYoung1208 commented on client/src/shared/js/api/adminData.js
> +    // myHttp('/api/cities', 'GET').then(x => x.json()),
убрал.

2021-01-23 21:42 UTC, ForeverYoung1208 commented on client/src/shared/js/common.js
> +  someErrors.forEach((e) => {
вот здесь я бы оставил без деструктуризации, т.к. это сервисная ф-я нормализации ошибок с сервера и предполагает некий словарь транслирования свойств объекта "e"  то я бы оставил это явно, если не принципиально.

2021-01-23 21:51 UTC, ForeverYoung1208 commented on client/src/shared/js/common.js
> +    if (e.message && e.path) {
Ошибка может  возинкать  на бэке в разных слоях,  пока есть 2 типа 
- либо ошибка валидации экспресс-валидатора (он выдает свою структуру ошибки), 
- либо ошбка базы данных, которую выдает seqelize в своей структуре.
Так или иначе, их надо где - то  нормализовать, вот решил что лучше пусть бэк выдает более полную, "raw" информацию, как минимум, проще дебажить.

2021-01-23 21:55 UTC, ForeverYoung1208 commented on client/src/shared/themes/mainTheme.js
> +    divider: '#875b20',
Ну, могу ошибаться, но как бы тема - это и есть глобальный сборник констант настройки темы. 
Во всяком случае, в процессе изучения вопроса (а я естественно копал, т.к. во первых материал впервые юзаю, а во вторых, пол дня гуглил как сменить цвет таблицы).....  другой методики не видел.

2021-01-23 21:56 UTC, ForeverYoung1208 commented on client/src/store/actions/actionTypes/cities.js
> +// export const CITIES_FETCH_OK = 'cities/FETCH_OK'
убрал.

2021-01-23 21:58 UTC, ForeverYoung1208 commented on client/src/store/actions/cities.js
> +  const { cities } = await apiGetCities()
действительно

2021-01-23 22:21 UTC, ForeverYoung1208 commented on client/src/store/reducers/admin.js
> +
Визуально кейсы отделять. Лично мне так легче ориентироваться в коде.
Ну... да, тут и так хорошо видно структуру. Убрал.

2021-01-23 22:21 UTC, ForeverYoung1208 commented on client/src/store/reducers/cities.js
> +const initialState = {
Не тут не понял, какие деструкторы?
Это же инициалиитуется initialState редьюсера...
А! Наверное, ты имеешь в виду дальше по самому редьюсеру... да, ок...  подеструктурировал.

Начальный статус переименовал в 'pristine' для большего соответствия смыслу.
В константы... хм.. Да, наверное, стоит.

2021-01-23 22:48 UTC, ForeverYoung1208 commented on client/src/store/reducers/cities.js
> +    case 'cities/fetch/fulfilled':
Ну они как бы генерируются createAsyncThunk-ом ( https://redux-toolkit.js.org/api/createAsyncThunk )
Показалось немного излишним запихивать их значения в константы, учитывая узкую целенаправленность этих экшенов.... 
Я - то вынес в константы... Но зачем ?

2021-01-23 22:49 UTC, ForeverYoung1208 commented on server/package.json
> +    "@material-ui/lab": "^4.0.0-alpha.57",
материал на бэк прокрался незаметно. )
удалил.

Фух, врооде все поправил, завтра постараюсь взяться за админку мастеров..
ух.. уже сегодня.

2021-01-25 15:46 UTC, yelyzavetak requested changes

2021-01-25 15:46 UTC, yelyzavetak commented on client/src/pages/AdminPage/MastersBlock/MastersBlock.jsx
> +        console.log('[action.payload]', action.payload)
лог

2021-01-25 15:46 UTC, yelyzavetak commented on client/src/pages/AdminPage/MastersBlock/MastersBlock.jsx
> +      if (action.type === 'masters/post/rejected') {
Если это экшн, то вынеси в константу. Все экшены длжны лежать в константах

2021-01-25 15:46 UTC, yelyzavetak commented on client/src/pages/AdminPage/MastersBlock/MastersBlock.jsx
> +        {/* <MasterAddDialog
Коммент

2021-01-25 15:46 UTC, yelyzavetak commented on client/src/pages/AdminPage/MastersBlock/_old_MastersBlock copy.jsx
> +          cityId: ['City', 'item-medium', (id) => (cities.find((c) => +c.id === +id).name)
Деструктор

2021-01-25 15:46 UTC, yelyzavetak commented on client/src/shared/js/common.js
> +    if (e.message && e.path) {
Лучше бы конечно ожидать ошибку в одном формате, напрмер: { code, message }. Давай это вынесем в отдельную задачу с самым низким приоритетом.

2021-01-25 15:46 UTC, yelyzavetak commented on client/src/shared/themes/mainTheme.js
> +    divider: '#875b20',
Сори, не увидела, что это файл темы. Вопрос снят.

2021-01-25 15:46 UTC, yelyzavetak commented on client/src/store/actions/masters.js
> +TODO: implement cityName update at masters state
По-моему тут не хватает //

2021-01-25 15:46 UTC, yelyzavetak commented on client/src/store/reducers/cities.js
> +const initialState = {
Да, я имела в виду дальше по редьюсеру.

2021-01-25 15:46 UTC, yelyzavetak commented on client/src/store/reducers/cities.js
> +    case CITIES_DELETE_REJECTED:
Зачем тут создавать константы для каждого вида запроса? Вполне достаточно будет одного CITIES_REJECTED и диспатчить его на любой эррор, который касается городов. Аналогично с остальными константами и сущностями.

Если тебе необходимо различать добавление, редактирование, удаление, то можно сделаь только 3:
CITIES_UPDATED
CITIES_ADDED
CITIES_DELETED

С pending - я так понимаю. что это loading, то тут, возможно, проще будет оставить все 3, но нужно смотреть. Я бы тоже до одной сократила

2021-01-25 15:46 UTC, yelyzavetak commented on client/src/store/reducers/statuses/statuses.js
> +export const PRISTINE = 'pristine'
Касаельно статусов - это костыль, который нужно убирать. Ставить статус для каждой сущности, это не очень хорошая идея. Если тебе нужно смотреть первичная это загрузка или нет, то ставь data: null и добавь переменную loading или pending, чтобы отличать первичную загрузку от обновлений.

Если проблема где-то в другом месте, то давай обсудим, как это лучше сделать.

2021-01-25 15:46 UTC, yelyzavetak commented on client/src/components/ItemsList/Item/Item.jsx
> +        fieldKeys.map((fieldKey) => {
Ок

2021-01-25 15:46 UTC, yelyzavetak commented on client/src/components/ReduxForm/RenderFieldSelect/RenderFieldSelectMUI.jsx
> +          options.map((o) => (
деструктор

2021-01-25 15:46 UTC, yelyzavetak commented on client/src/pages/AdminPage/CitiesBlock/CitiesBlock.jsx
> +      if (action.type === 'cities/put/rejected') {
в константу

2021-01-25 15:50 UTC, yelyzavetak commented on client/src/pages/AdminPage/CitiesBlock/CitiesBlock.jsx
> +    dispatch(setErrorMessage(''))
Я спуллила ветку и посмотрела в чем проблема. Да, с useEffect немного костыль выходит. В идеале, ошибку необходимо хранить в сторе сущности, например, если запрос на обновление города пришел с ошибкой, то для редьюсера городов необходимо вызвать экшн, который диспатчит эту ошибку и обновляет поле ошибки в сторе. Таким образом, при обновлении списка, при успешном добавлении города в редьюсере можно смело писать, что ошибка null, в нужном кейсе и не изобретать велосипед.

2021-01-25 15:51 UTC, yelyzavetak commented on client/src/pages/AdminPage/CitiesBlock/CityEditDialog/CityEditDialog.jsx
> +    data.find((c) => +c.id === +cityId),
Ок

2021-01-25 15:51 UTC, yelyzavetak commented on client/src/shared/js/common.js
> +  someErrors.forEach((e) => {
По поводу ошибок написала ниже - вынесем отдельно и сделаем потом. Оставляй пока так

2021-01-25 15:52 UTC, yelyzavetak commented on client/src/store/reducers/admin.js
> +
Пустые строки да, но пробелы в пустой строке разве prettier не убирает? Против пустых строк для отделения блоков с логикой я ничего против не имею

2021-01-25 15:55 UTC, yelyzavetak commented on client/src/store/reducers/cities.js
> +    case 'cities/fetch/fulfilled':
Хм, я его раньше никогда не использовала. А в каких целях createAsyncThunk тебе понадобился? Если кратко

2021-01-25 15:55 UTC, yelyzavetak commented on client/src/pages/AdminPage/MastersBlock/MastersBlock.jsx
> +      if (action.type === 'masters/post/rejected') {
Это от createAsyncThunk ?

2021-01-25 15:55 UTC, yelyzavetak commented on client/src/pages/AdminPage/CitiesBlock/CitiesBlock.jsx
> +      if (action.type === 'cities/put/rejected') {
createAsyncThunk ?

2021-01-25 17:37 UTC, ForeverYoung1208 commented on client/src/store/reducers/cities.js
> +    case 'cities/fetch/fulfilled':
Как я понял, оно свежее, недавно впихнули. Просто  сокращает весь этот бойлерплейт-код стандартных экшенов которые обычно пишутся при http запросе. Генерирует три страндартных экшена pending / fulfilled / rejected

2021-01-28 19:04 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/MastersBlock/MastersBlock.jsx
> +        console.log('[action.payload]', action.payload)
ну да, ну да, андер канстракшен, не закончил еще с мастерами.

2021-01-28 19:08 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/MastersBlock/MastersBlock.jsx
> +      if (action.type === 'masters/post/rejected') {
да,  экшен, сгенерированный createAsyncThunk-ом. Кстати я их таки забил в константы для порядка.

2021-01-28 19:09 UTC, ForeverYoung1208 commented on client/src/store/actions/masters.js
> +TODO: implement cityName update at masters state
Это чтобы быстро найти место где продолжить

2021-01-28 20:33 UTC, ForeverYoung1208 commented on client/src/store/reducers/cities.js
> +    case CITIES_DELETE_REJECTED:
ну вот смотри  client/src/store/actions/cities.js (стр. 11) там такой экшкн креэйтор:
---
export const fetchCities = createAsyncThunk('cities/fetch', async () => {
  const cities = await apiGetCities()
  return cities
})
---
он генерирует 3 экшена: cities/fetch/pending, cities/fetch/fulfilled, cities/fetch/rejected
(см. https://redux-toolkit.js.org/api/createAsyncThunk) ну и диспатчит их в зависимости от состояния промиса.
Достаточно удобно и скоращает бойлерплейт код.

НО тут уж никуда не денешься - или полагатья на плюшки  @reduxjs/toolkit/createAsyncThunk и ничего не сокращать
или перепивсывать всё по старинке руками.
я б оставил createAsyncThunk.

2021-01-28 20:43 UTC, ForeverYoung1208 commented on client/src/store/reducers/statuses/statuses.js
> +export const PRISTINE = 'pristine'
Согласен. Тем более они нигде не используются - наверное, бы какой - то костыль, который уже выпилил, а статусы остались.
Ну, проверю еще, но пока что убрал, и нигде ни на что не повлияло.

2021-01-28 20:44 UTC, ForeverYoung1208 commented on client/src/components/ReduxForm/RenderFieldSelect/RenderFieldSelectMUI.jsx
> +          options.map((o) => (
ok

2021-01-28 20:47 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/CitiesBlock/CitiesBlock.jsx
> +      if (action.type === 'cities/put/rejected') {
Да. Его экшен. Поменял на константу.

2021-01-29 13:50 UTC, yelyzavetak commented on client/src/store/reducers/cities.js
> +    case 'cities/fetch/fulfilled':
Хорошо, давай оставим логику с createAsyncThunk. Хорошая мысль

2021-01-29 13:52 UTC, yelyzavetak commented on client/src/pages/AdminPage/MastersBlock/MastersBlock.jsx
> +        {/* <MasterAddDialog
Лучше не пушить в пулл реквест изменения, которые еще не готовы. Таким образом я смотрю то, что еще не готово и потом буду это смотреть по второму разу. В пулл реквесте должны быть изменения, готовы к просмотру. Если то тестовый пулл, то помечай его как драфт.

2021-01-29 13:53 UTC, yelyzavetak commented on client/src/store/actions/masters.js
> +TODO: implement cityName update at masters state
Так делать нельзя, так как ветка в пулл реквесте должна быть рабочая. Вдруг я захочу посмотреть как оно выглядить, а собрать не смогу. Или решу смержить и таким образом в девелопе окажется нерабочая сборка

2021-01-29 13:53 UTC, yelyzavetak commented on client/src/store/reducers/cities.js
> +    case CITIES_DELETE_REJECTED:
Хорошо, давай оставим логику с createAsyncThunk. Хорошая мысль

2021-01-29 15:00 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/MastersBlock/MastersBlock.jsx
> +        {/* <MasterAddDialog
Хм...  Ведь пулл реквест создан на всю ветку...
Получается, для того, чтобы мне, например, в своих личных целях делать коммиты (у меня несколько систем где я попеременно кодю), и не муарить в этом пул реквесте, то получается.... нужно создавать еще одну ветку (например, "feature/material/under-construnction", и по мере готовности вмерживать ее сюда? Верно?

2021-02-01 16:26 UTC, yelyzavetak requested changes

2021-02-01 16:26 UTC, yelyzavetak commented on client/src/components/ReduxForm/RenderFieldInput/RenderFieldInputMUI.jsx
> +    return (error && error) || (warning && warning)
Перепиши пожалуйста на читабельную версию с if-else

2021-02-01 16:26 UTC, yelyzavetak commented on client/src/components/ReduxForm/RenderFieldSelect/RenderFieldSelectMUI.jsx
> +    return (error && error) || (warning && warning)
The same

2021-02-01 16:26 UTC, yelyzavetak commented on client/src/pages/AdminPage/CitiesBlock/CityAddDialog/CityAddDialog.jsx
> +  const city = {}
Зачем тут этот объект? Он где-то модифицриуется? Если да, то это необходимо делать через локальный стейт или через редакс. Если есть такая возможность.

Прежде, чем брать в работу, напиши пожалуйста сколько у тебя уйдет на это времени, возможно сделаешь это в следующем пулл реквесте.

2021-02-01 16:26 UTC, yelyzavetak commented on client/src/pages/AdminPage/MastersBlock/MasterAddDialog/MasterAddDialog.jsx
> +  const master = {}
The same

2021-02-01 16:26 UTC, yelyzavetak commented on client/src/store/reducers/cities.js
> +  let newCities = []
не используй тут глобальные массивы

2021-02-01 16:26 UTC, yelyzavetak commented on client/src/store/reducers/cities.js
> +      newCities[newCityIdx] = payload
Тут используй map вместо findIndex

2021-02-01 16:26 UTC, yelyzavetak commented on client/src/store/reducers/masters.js
> +  let newMasters = []
The same

2021-02-01 16:26 UTC, yelyzavetak commented on client/src/store/reducers/masters.js
> +      const newMasterIdx = state.data.findIndex(
The same

2021-02-01 16:26 UTC, yelyzavetak commented on client/src/pages/AdminPage/MastersBlock/MastersBlock.jsx
> +      dispatch(setErrorMessage(''))
На сколько я вижу, то в редьюсере ты ставить ошибке null. До сих пор необходимо тут это диспатчить?

2021-02-02 07:49 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/CitiesBlock/CityAddDialog/CityAddDialog.jsx
> +  const city = {}
Там дальше используется в  
`<CityForm city={city} onSubmit={addHandler} />`
(CityForm  одна и для добавления и для редактирования, инициализируется данными из пропса сity)
Убрать вообще не проблема, тогда, например:
`<CityForm city={{}} onSubmit={addHandler} />`
или вообще убрать: 
`<CityForm onSubmit={addHandler} />`
но тогда внутри CityForm поставить проверку наличия пропса. (Но мне, если честно, не нравятся опциональные параметры / пропсы но это такое, вкусовщина).

2021-02-02 08:16 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/MastersBlock/MastersBlock.jsx
> +      dispatch(setErrorMessage(''))
Имеешь в виду, наверное, не null, а  пустую строку? Ну да, тут сбрасывается сообщение об ошибке, если такое было.
Помнишь,  еще в предыдущем варианте  (до MUI) ты мне писала что не исчезают ошибки... так вот. тут они очищаются.  Можно, конечно, на выходе из редактирования поставить, но это мне кажется хуже по ряду причин.

2021-02-02 15:12 UTC, yelyzavetak commented on client/src/pages/AdminPage/CitiesBlock/CityAddDialog/CityAddDialog.jsx
> +  const city = {}
Я поняла, хорошо. Оставим так

2021-02-02 15:14 UTC, yelyzavetak commented on client/src/pages/AdminPage/MastersBlock/MastersBlock.jsx
> +      dispatch(setErrorMessage(''))
Нет, я имела в виду, что если ты обнуляешь ошибку тут: https://github.com/ForeverYoung1208/clmasters/pull/12/files#diff-e741eadebf111913d9bfb531e114f36752db15701cc1c7a4201e905f7ba6fc31R40
То зачем из компонента диспатчить? Или это разные ошибки?

2021-02-03 21:45 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/MastersBlock/MastersBlock.jsx
> +      dispatch(setErrorMessage(''))
да, тут получается такая штука... если в кратце... если ошибка сабмита редакс-формы по какой - то сущности  то она идет через конкретный стейт и редьюсер сущности (об-null-яесть принеобходимости редьюсером), хендлится и отображается  соответствующей редакс формой и инпутом.
.... если же это какая - то общая ошибка (ну, например, ошибка удаления,  или какая - то другая общая ошибка), то она идет через "общий" стейт main:{errorMessage}  и отображается уже моим компонентом ErrorMessage

2021-02-03 21:45 UTC, ForeverYoung1208 commented on client/src/store/reducers/masters.js
> +      const newMasterIdx = state.data.findIndex(
ок

2021-02-03 21:45 UTC, ForeverYoung1208 commented on client/src/store/reducers/masters.js
> +  let newMasters = []
ок

2021-02-03 21:45 UTC, ForeverYoung1208 commented on client/src/store/reducers/cities.js
> +      newCities[newCityIdx] = payload
ок

2021-02-03 21:46 UTC, ForeverYoung1208 commented on client/src/store/reducers/cities.js
> +  let newCities = []
ок, пришлось напрячь фантазию на имена const - ам   )))

2021-02-03 21:54 UTC, ForeverYoung1208 commented
вроде бы всё поправил.

2021-02-04 14:40 UTC, yelyzavetak approved these changes

2021-02-04 19:29 UTC, merged