Feature/usersMUI
ForeverYoung1208/clmasters pull request #14
Opened 2021-02-04 21:05 UTC by ForeverYoung1208

Сделал в админке пользователей по аналогии с городами/мастерами.
Остались еще в админке сами заказы, начну в другой ветке.

2021-02-11 12:50 UTC, yelyzavetak requested changes

2021-02-11 12:50 UTC, yelyzavetak commented on client/src/pages/AdminPage/UsersBlock/UserEditDialog/UserEditDialog.jsx
> +import { DraggablePaper } from '../../../../components/Material/DraggablePaper/DraggablePaper'
Я посмотрела на сайте, как выглядит новая верстка и не поняла, где ты используешь drag'n'drop в таблицах? Если он просто для "красоты", то лучше его заменить на любую другую обёртку, но не нужно использовать Draggable просто так. Что думаешь?

2021-02-11 12:50 UTC, yelyzavetak commented on client/src/pages/AdminPage/UsersBlock/UsersBlock.jsx
> +const ROWS_PER_PAGE_OPTIONS = [10, 20, 50]
Если эти константы едины для всех таблиц, то лучше их вынести в отдельный файл

2021-02-11 13:01 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/UsersBlock/UserEditDialog/UserEditDialog.jsx
> +import { DraggablePaper } from '../../../../components/Material/DraggablePaper/DraggablePaper'
ээээээто не в таблице,  это формочка редактирования/создания может "тягаться"...
с таблицей там ничеготакого.

2021-02-11 13:12 UTC, yelyzavetak commented on client/src/pages/AdminPage/UsersBlock/UserEditDialog/UserEditDialog.jsx
> +import { DraggablePaper } from '../../../../components/Material/DraggablePaper/DraggablePaper'
Ок, пересмотрю и отпишусь

2021-02-11 14:36 UTC, yelyzavetak commented on client/src/pages/AdminPage/UsersBlock/UserEditDialog/UserEditDialog.jsx
> +import { DraggablePaper } from '../../../../components/Material/DraggablePaper/DraggablePaper'
Посмотрела, выглядит норм. Вопрос снят

2021-02-17 20:17 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/UsersBlock/UsersBlock.jsx
> +const ROWS_PER_PAGE_OPTIONS = [10, 20, 50]
Перенес в тему материала. Не знаю насколько это ОК, но мне кажется логично и лучше, чем плодить дополнитльные файлы.

2021-02-22 15:55 UTC, yelyzavetak approved these changes

2021-02-22 19:49 UTC, merged