Feature/ordersMUI
ForeverYoung1208/clmasters pull request #15
Opened 2021-02-17 20:54 UTC by ForeverYoung1208

Последняя часть админки, переписанная на material-UI,  убран 'section_key', убран 'admindata'. Вмержил последние исправления замечания по констатам с ветки пользователей.

2021-02-22 16:27 UTC, yelyzavetak requested changes

2021-02-22 16:27 UTC, yelyzavetak commented on client/src/pages/InfoPage/InfoPage.jsx
> +  // getOrdersBy,
Зачем тут комментарий? Лучше удалить

2021-02-22 16:27 UTC, yelyzavetak commented on client/src/pages/InfoPage/InfoPage.jsx
> +    alert (' dispatch(getOrdersBy({ email: searchString }))')
Забыл удалить

2021-02-22 16:27 UTC, yelyzavetak commented on client/src/pages/InfoPage/InfoPage.jsx
> +    // dispatch(clearOrderResult());
и тут

2021-02-22 16:27 UTC, yelyzavetak commented on client/src/pages/InfoPage/InfoPage.jsx
> +              alert ('dispatch(clearOrders());')
и тут. Я дальше не буду комментировать подобное - пройдись и удалить

2021-02-22 16:27 UTC, yelyzavetak commented on client/src/components/ReduxForm/RenderFieldTime/RenderFieldTimeMUI.jsx
> +    if (warning) return warning
Не проще ли:
`return error || warning`
?

2021-02-22 20:25 UTC, ForeverYoung1208 commented on client/src/pages/InfoPage/InfoPage.jsx
> +              alert ('dispatch(clearOrders());')
В InfoPage пришлось забивать в комментарии части, которые сломались/неактуальны из-за изменений в структуре приложения (убирается 'sectionKey', из стейта убираются части 'admin', 'vocabluaries' чтобы оставить только бизнесовые сущности). Соответственно меняются экшены и редьюсеры, поэтому некоторые части и вне именений перестают работать.  

Я бы предложил не исправлять тут InfoPage, т.к. всё это уже исправлено и переделано в другой ветке (feature/findMasterMUI Updated 23 hours ago by ForeverYoung1208)

Если править тут, при мерже полезут конфликты. 

Давай уже эту ветку волью в мастер, потом  - в findMasterMUI, причешу ее еще немного (чуток на выходных не успел) и сделаю pull request. Это уже будет какой - то конец перехода на материал. Ну начало конца )))

2021-02-22 20:28 UTC, ForeverYoung1208 commented on client/src/components/ReduxForm/RenderFieldTime/RenderFieldTimeMUI.jsx
> +    if (warning) return warning
Действительно, проще.

2021-02-25 19:29 UTC, yelyzavetak commented on client/src/pages/InfoPage/InfoPage.jsx
> +              alert ('dispatch(clearOrders());')
Хорошо, комменты можешь оставить пока, но алерты удали пожалуйста. Любые логи не должны присутствовать в мастере

2021-02-27 12:07 UTC, ForeverYoung1208 commented on client/src/pages/InfoPage/InfoPage.jsx
> +              alert ('dispatch(clearOrders());')
ок, убрал.
слил с более актуальной веткой feature/findMastersMUI  и разрешил там конфликты:
https://github.com/ForeverYoung1208/clmasters/pull/16

2021-02-27 15:12 UTC, merged