Feature/responsive
ForeverYoung1208/clmasters pull request #19
Opened 2021-03-14 16:14 UTC by ForeverYoung1208

2021-03-15 15:08 UTC, yelyzavetak requested changes

2021-03-15 15:08 UTC, yelyzavetak commented on client/src/pages/AdminPage/MastersBlock/CompactMaster/CompactMaster.jsx
> +      <div className="admin-page__item--compact__row"><span>Comment:</span> <span>{comment} </span></div>
Можно создать отдельный компонент, куда передавать label, value и тут использовать его, вместо копирования всей разметки.

2021-03-15 15:08 UTC, yelyzavetak commented on client/src/pages/AdminPage/MastersBlock/CompactMaster/CompactMaster.jsx
> +)
До сих пор кажется, что с prettier что-то не так и он не до конца настроен

2021-03-15 15:08 UTC, yelyzavetak commented on client/src/pages/AdminPage/OrdersBlock/CompactOrder/CompactOrder.jsx
> +      <div className="admin-page__item--compact__row"><span>Comment:</span> <span>{comment} </span></div>
Создай отдельный компонент, можно в этом же файле, а можно создать глобальный (класс же везде один) и использовать его и для CompactMaster

2021-03-15 15:08 UTC, yelyzavetak commented on client/src/pages/AdminPage/UsersBlock/CompactUser/CompactUser.jsx
> +      <div className="admin-page__item--compact__row"><span>Is admin?:</span> <span>{isAdmin ? 'Yes' : 'No'} </span></div>
The same

2021-03-15 15:08 UTC, yelyzavetak commented on client/src/shared/js/normalizeFormSubmitError.js
> +      if (e.param === 'order' && /.*master is busy at given time.*/.test(e.msg)) {
Не очень поняла это изменение, зачем тебе искать вхождения?

2021-03-15 20:07 UTC, ForeverYoung1208 commented on client/src/components/Header/Header.jsx
> +          <div>&nbsp;</div>
Респонсивность же. Емейл залогиненого пользователя длинный, пришлось прятать его в выпадающий дропдаун, оставлять только иконку. Ну а поскольку там меняется не только верстка но и сам компонент выпадающего дропдауна, то вот решил сделать не через css селекторы, а рендерить разны компоненты. Кстати от css постарался по возможности отказаться в пользу styled components, мне показалось что материал тяготеет именно к стилизованным копонентам - темизация там..
Если же ты про пробел &nbsp, то нужен какой-то блок, чтобы flex нормально распределял место при  justifyContent: 'space-between', не ломая структуру. Можно отказаться, изменяя верстку (сделать justifyContent: start), но тогда поведение меню поменяется(будет не центрироваться, а слева). Мне кажется, это хуже.

2021-03-15 20:09 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/MastersBlock/CompactMaster/CompactMaster.jsx
> +)
Забыл запустить после редактирования.

2021-03-15 20:10 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/MastersBlock/CompactMaster/CompactMaster.jsx
> +      <div className="admin-page__item--compact__row"><span>Comment:</span> <span>{comment} </span></div>
Можно... щас сделаем.

2021-03-15 20:12 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/OrdersBlock/CompactOrder/CompactOrder.jsx
> +      <div className="admin-page__item--compact__row"><span>Comment:</span> <span>{comment} </span></div>
да, конечно. Я за отдельный компонент, сделаю.

2021-03-15 20:28 UTC, ForeverYoung1208 commented on client/src/shared/js/normalizeFormSubmitError.js
> +      if (e.param === 'order' && /.*master is busy at given time.*/.test(e.msg)) {
Ну, тут с бэкэнда приезжает ошибка не по конкретному полю, а в целом по сущности (в принципе, бэку непонятно это ошибка во времени, мастере или пипе часов - просто эти три параметра между собой конфликтуют, поэтому с бэка возвращаю именно ошибку во всей сущности)... А, теоретически, у этой сущности  "order" могут в будущем быть и другие ошибки. Чтобы они все бездумно  не попадали в поле "OnTime" формы такая себе проверочка-страховочка.

2021-03-15 21:52 UTC, ForeverYoung1208 commented on client/src/components/Header/Header.jsx
> +          <div>&nbsp;</div>
Пфффф отэто я загнал пердюмонокль с этим &nbsp; )))))
Убрал ))))

2021-03-15 21:53 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/UsersBlock/CompactUser/CompactUser.jsx
> +      <div className="admin-page__item--compact__row"><span>Is admin?:</span> <span>{isAdmin ? 'Yes' : 'No'} </span></div>
угу

2021-03-15 21:58 UTC, ForeverYoung1208 commented
поправил всё.

2021-03-17 14:51 UTC, yelyzavetak approved these changes

2021-03-17 20:29 UTC, merged