Feature/add price and activeness
ForeverYoung1208/clmasters pull request #20
Opened 2021-03-21 20:20 UTC by ForeverYoung1208

Вроде бы сделал. (добавил признак активности к мастерам и городам, добавил цену заказа).
Измененные файлы проехал Prettier-ом.

2021-03-24 17:52 UTC, yelyzavetak requested changes

2021-03-24 17:52 UTC, yelyzavetak commented on client/src/pages/AdminPage/MastersBlock/MasterForm/MasterForm.jsx
> +    return cities.filter((city) => city.isActive === true)
Не обязательно ставить такую проверку, если isActive - boolean, достаточно просто
return cities.filter((city) => city.isActive)

2021-03-24 17:52 UTC, yelyzavetak commented on client/src/pages/AdminPage/OrdersBlock/OrderForm/OrderForm.jsx
> +  change,
Что делает change? Может стоит назвать как-то более информативно?

2021-03-24 17:52 UTC, yelyzavetak commented on client/src/pages/AdminPage/OrdersBlock/OrderForm/OrderForm.jsx
> +    let repairHours = timeStrToHours(selectedClock?.repairTime)
Не поняла смысл такой сложной функции timeStrToHours. Каждый тип часов имеет свой размер веремни для починки - 1, 2, 3 часа. Это хардкодный параметр не требующий вычисления. Можно понимать, сколько займет времения починка по типу часов.

2021-03-24 17:52 UTC, yelyzavetak commented on client/src/pages/AdminPage/MastersBlock/MasterForm/MasterForm.jsx
> +            validate={validators.isDecimal}
Со стороны админа, если я введу значение 5, вместо 5.00, мне выдаст ошибку? Не очень дружественный интерфейс, если я правильно поняла

2021-03-24 17:52 UTC, yelyzavetak commented on client/src/pages/MastersPage/OrderForm/OrderForm.jsx
> +    ?.filter((master) => master.isActive === true)
Не обязательно === true, достаточно прочто master.isActive. Дальше писать не буду, поправь пжл везде

2021-03-24 21:56 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/MastersBlock/MasterForm/MasterForm.jsx
> +    return cities.filter((city) => city.isActive === true)
мде. Как - то на автомате наверное..
Туповато вышло ))))

2021-03-24 22:00 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/OrdersBlock/OrderForm/OrderForm.jsx
> +  change,
ну, это не моё))) - это метод для изменения данных формы, инжектится самой редаксФормой..
переименовал его в более читабельное название.

2021-03-24 22:13 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/OrdersBlock/OrderForm/OrderForm.jsx
> +    let repairHours = timeStrToHours(selectedClock?.repairTime)
Ну, у меня он изначально архитектурно - не хардкорный, а тянется из базы... такая себе закладка на случай, если придется добавлять другие типы часов или изменять сроки ремонта... 
Выпилить и захардкодить это будет достаточно сложно, да и зачем!?
.... Хм.... плюс еще... вреннее минус )))  захардкодить - вообще плохо - возникнет 2 источника правды о сроке ремонта - на фронте и на бэке, теоретически,... наверное...  это место для ошибки... и тогда информация которая презентуется на фронте  юзеру будет нерелевантно обрабатываться на сервере в момент вычисления наличия свободных мастеров... 
Короче, я бы оставил.

2021-03-24 22:23 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/MastersBlock/MasterForm/MasterForm.jsx
> +            validate={validators.isDecimal}
да нет, вроде нормально - там дробная часть опционально.
/^\d{1,6}(\.\d{1,2})?$/
три знака уже выдаст ошибку..
Да, проверил, так и работет. Точка и копейки - опционально.

2021-03-24 22:23 UTC, ForeverYoung1208 commented on client/src/pages/MastersPage/OrderForm/OrderForm.jsx
> +    ?.filter((master) => master.isActive === true)
+

2021-03-24 22:25 UTC, ForeverYoung1208 commented
поправил.

2021-03-24 22:30 UTC, ForeverYoung1208 commented
вмержил последние багфиксы

2021-03-26 13:39 UTC, yelyzavetak requested changes

2021-03-26 13:39 UTC, yelyzavetak commented on client/src/pages/AdminPage/OrdersBlock/OrderForm/OrderForm.jsx
> +    let repairHours = timeStrToHours(selectedClock?.repairTime)
Я пересмотрела твои изменения касательно цены и если ты очень хочешь парсить строку, то делай это готовыми пакетами: moment.js, luxon and etc, а не самописными хелперами
Но я не понимаю почему цена считается на фронте? Она должна высчитываться окончательно на беке, на фронте можно посчитать просто чтобы показть юзеру. Или я что-то пропустила?

2021-03-26 13:59 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/OrdersBlock/OrderForm/OrderForm.jsx
> +    let repairHours = timeStrToHours(selectedClock?.repairTime)
По поводу парсинга готовыми пакетами - ессно, я сначала по ним погуглил, но, как и ожидалось, конвертации строки в дробную (десятичную) часть часа там такого нет (или не нашел, но навряд ли). А поскольку рейт почасовой то нужна именно дробная часть часа (1ч 30 мин = 1,5 часа) - руками это написать вообще 2 минуты.
Хотя я понимаю предпочтительность библиотек, но мне кажется, не в этом случае.

Цена считается на фронте да... и чтобы показать, и отправить на бэк. Не знаю, надо ли ее там вычислять/пересчитывать, или можно принять ее как часть заказа с фронта.  Тут нужна установка. Если надо вычислять на бэке, а информацию с фронта игнорить - запилю, там не должно быть сложно. Можно даже проверку сделать на соответствие информации.

2021-03-26 14:08 UTC, yelyzavetak commented on client/src/pages/AdminPage/OrdersBlock/OrderForm/OrderForm.jsx
> +    let repairHours = timeStrToHours(selectedClock?.repairTime)
Поищи пожалуйста либу, которая это делает, если не найдешь, то напиши - будем думать.

Цена заказа должна полностью считаться на беке, с фронта ты ее не отправляешь, а просто считаешь чтобы показать юзеру. Проверка на соответствие не требуется, так как не нужно ее отсылать на бек.

2021-03-26 15:11 UTC, yelyzavetak commented on client/src/pages/AdminPage/OrdersBlock/OrderForm/OrderForm.jsx
> +    let repairHours = timeStrToHours(selectedClock?.repairTime)
Если я тебя правильно поняла, то у momentjs есть такая функция: https://stackoverflow.com/questions/21255268/how-to-convert-time-hhmm-to-decimal-form-with-momentjs

2021-03-26 15:39 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/OrdersBlock/OrderForm/OrderForm.jsx
> +    let repairHours = timeStrToHours(selectedClock?.repairTime)
Да, это оно. Круто, я не нашел. (Хотя я, конечно, искал больше в date-fns т.к. он уже есть в проекте)  Но и в целом смотрел. мде. Думаешь, стоит из-за этого целую библиотеку тащить?

2021-03-26 15:54 UTC, yelyzavetak commented on client/src/pages/AdminPage/OrdersBlock/OrderForm/OrderForm.jsx
> +    let repairHours = timeStrToHours(selectedClock?.repairTime)
Я забыла, что у тебя не момент.

Я поискала и в date-fns похоже нет такого, но я не углублялась. Но зато тут из строки можно отдельно получить в числах часы и минуты. Минуты первести по пропорции - minutes * 100/60

И прибавить это к часам. Во всяком случае не нужно будет заморачиваться и самому парсить строки

Ради этого подключать момент не стоит, давай попробуем с date-fns

2021-03-28 18:53 UTC, ForeverYoung1208 commented on client/src/pages/AdminPage/OrdersBlock/OrderForm/OrderForm.jsx
> +    let repairHours = timeStrToHours(selectedClock?.repairTime)
... Внезапно такая мелочь заняла много времени - в date-fns  столконулся с тем, что он может получить часы и минуты не из строки, а из объекта даты, а если формировать дату из строки типа "DD:mm:ss" возникает путаница с таймзоной, с которой я и увяз так прилично (реально распарсить руками быстрее ))) .....  Но по ходу нашел как можно обойтись вообще без сторонней библиотеки, лишь с помощью нативного конструктора даты и факта того, что дата в JS - это миллисекунды от 1 янв. 1970г., что и реализовал как на фронте, так и на бэке.

2021-03-28 19:00 UTC, ForeverYoung1208 commented
внес правки в расчет стоимости на фронте, сделал расчет цены на бэке.

2021-03-29 14:53 UTC, yelyzavetak approved these changes

2021-03-29 20:18 UTC, merged