Feature/stripe
ForeverYoung1208/clmasters pull request #43
Opened 2021-07-03 18:36 UTC by ForeverYoung1208

Ну, по крайней мере, в тестовом окружении, без реальных платежей, работает. Только в окружении раработки надо клиента stripe запускать чтобы оно события перехватывало и форвардило на бэкэнд который на localhost:5000:

stripe listen --forward-to localhost:5000/api/payment/webhook

https://trello.com/c/pM4SbDtJ

2021-07-05 13:40 UTC, yelyzavetak requested changes

2021-07-05 13:40 UTC, yelyzavetak commented on client/src/pages/InfoPage/InfoPage.jsx
> +function useQuery() {
use arrow functions

2021-07-05 13:40 UTC, yelyzavetak commented on client/src/pages/InfoPage/OrdersInfo/OrdersInfo.jsx
> +                    {order.payedSum ? order.payedSum : '0'}
order.payedSum || '0'

2021-07-05 13:40 UTC, yelyzavetak commented on client/src/pages/InfoPage/OrdersInfo/OrdersInfo.jsx
> +                    {(Math.abs(order.payedSum - order.price) < 0.009)
Что такое 0.009, Стоит как-то назвать и вынести в константы, а не оставлять как магическое число

2021-07-05 13:40 UTC, yelyzavetak commented on client/src/pages/InfoPage/OrdersInfo/OrdersInfo.jsx
> +                      ? null
Зачем ренедерить нулл? Нужно написать так, чтоб нода рендерилась только если условие выполняется

2021-07-05 13:40 UTC, yelyzavetak commented on client/src/pages/MastersPage/MastersPage.jsx
> +        </Route> */}
нужен этот кусок кода?

2021-07-05 13:40 UTC, yelyzavetak commented on server/models/order.js
> +      return ( Math.abs(this.payedSum - this.price) < 0.01)
Не очень поняла, зачем такое условие?

2021-07-05 13:41 UTC, yelyzavetak commented
Было бы здорово называть коммиты более иформативно, даже если ты просто сохранял прогресс - напиши что именно ты сделал в этом коммите

2021-07-06 20:20 UTC, ForeverYoung1208 commented on client/src/pages/InfoPage/InfoPage.jsx
> +function useQuery() {
поправил

2021-07-06 20:21 UTC, ForeverYoung1208 commented on client/src/pages/InfoPage/OrdersInfo/OrdersInfo.jsx
> +                    {order.payedSum ? order.payedSum : '0'}
поправил.

2021-07-06 20:21 UTC, ForeverYoung1208 commented on client/src/pages/InfoPage/OrdersInfo/OrdersInfo.jsx
> +                    {(Math.abs(order.payedSum - order.price) < 0.009)
поправил, вынес.

2021-07-06 20:22 UTC, ForeverYoung1208 commented on client/src/pages/InfoPage/OrdersInfo/OrdersInfo.jsx
> +                      ? null
переписал.

2021-07-06 20:23 UTC, ForeverYoung1208 commented on client/src/pages/MastersPage/MastersPage.jsx
> +        </Route> */}
неа. огрызок неактуальной задумки, недовыпилил. 
Теперь довыпилил. 
Кстати перенес компонент <PaymentBlock/> к компонентам, мне кажется так логичнее.

2021-07-06 20:26 UTC, ForeverYoung1208 commented on server/models/order.js
> +      return ( Math.abs(this.payedSum - this.price) < 0.01)
Ну как, это метод объекта для того, чтобы понять оплачен заказ или нет. Если сумма оплаты отличается от стоимости менее чем на копейку - то оплачен.  По алогии с предыдузим замечанием  вынес "магическое число" в константу.

2021-07-06 20:29 UTC, ForeverYoung1208 commented
> Было бы здорово называть коммиты более иформативно, даже если ты просто сохранял прогресс - напиши что именно ты сделал в этом коммите

иногда сложно вспомнить и выразить кратко (например интеграция оплаты затронула назквозь всю структуру - от базы данных до фронтенда...  но постараюсь.

2021-07-09 07:49 UTC, yelyzavetak approved these changes

2021-07-11 14:02 UTC, merged