error text at admin/orders is humanized.
ForeverYoung1208/clmasters pull request #7
Opened 2020-12-19 19:17 UTC by ForeverYoung1208

карточка:  https://trello.com/c/kLOU5PJj

2020-12-24 10:31 UTC, yelyzavetak requested changes

2020-12-24 10:31 UTC, yelyzavetak commented on client/src/HOC/withHumanizeError.jsx
> +    ['email must be unique', 'Email must be unique'],
['email must be unique', 'Email must be unique'], - Зачем дублировать?

2020-12-24 13:22 UTC, ForeverYoung1208 commented on client/src/HOC/withHumanizeError.jsx
> +    ['email must be unique', 'Email must be unique'],
Первый элемент - это паттерн, который ищется в тексте ошибки с бэка  (идентификатор ошибки) , второй- человеческое представлене ошибки, для отобаржения. В данном случае совпадает, ну только отбрасывается остальной мусор.
Ну вот такая система очеловечивания ошибок )

2020-12-24 13:26 UTC, yelyzavetak commented on client/src/HOC/withHumanizeError.jsx
> +    ['email must be unique', 'Email must be unique'],
Я имела в виду, что строки 8 и 9 одинаковые. Зачем?

2020-12-24 13:59 UTC, ForeverYoung1208 commented on client/src/HOC/withHumanizeError.jsx
> +    ['email must be unique', 'Email must be unique'],
Ха, наверное не глянул что такая уже есть. Уберу.

2020-12-29 16:37 UTC, yelyzavetak approved these changes

2021-01-03 15:14 UTC, merged